services:
  db:
    image: postgres:15-alpine
    container_name: vete_saas_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - vete_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vete_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vete.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  vete_data: